# docker config to build images. Used locally
version: '3.7'

services:
  backend:
    build: src/
    image: evanrthomas/instant-runoff-app-backend
    ports:
      - '8000:8000'

  frontend:
    build: frontend/
    image: evanrthomas/instant-runoff-app-frontend
    ports:
      - '3000:3000'
