#!/bin/bash
set -euxo pipefail

echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

docker-compose -f docker-compose.build.yaml build
docker-compose -f docker-compose.build.yaml push
