#!/bin/bash
set -euxo pipefail


# copy new version of code
cat docker-compose.prod.yaml | ssh -i $DEPLOY_KEY_PATH $DEPLOY_USER@$DEPLOY_INSTANCE """
cat - > ~/docker-compose.yaml
docker-compose -f ~/docker-compose.yaml pull
docker-compose -f ~/docker-compose.yaml down
docker-compose -f ~/docker-compose.yaml up -d
"""
